// components/Page.vue
<template>
  <div>
    <header class="header">
      <div class="flex items-center">
        <span>Cotowali</span>
      </div>
      <nav>
        <ul class="flex h-full">
          <li><a class="nav-item-anchor" href="/docs">Docs</a></li>
          <li>
            <a
              class="nav-item-anchor"
              href="https://github.com/cotowali/cotowali"
              target="_blank"
              rel="external noopener noreferrer"
            >GitHub</a>
          </li>
        </ul>
      </nav>
    </header>

    <div class="page">
      <template v-if="$slots.left">
        <slot name="left" />
      </template>
      <div class="content">
        <main>
          <slot />
        </main>

        <footer class="footer">
          <p class="text-sm">
            Copyright &copy; 2021 The Cotowali Authors
          </p>
        </footer>
      </div>
      <template v-if="$slots.right">
        <slot name="right" />
      </template>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'Page',
})
</script>

<style>
  body {
    @apply text-white;
    @apply bg-dark;
  }
</style>

<style scoped>
  .page {
    @apply flex justify-between;
    @apply min-h-screen w-full;
    @apply bg-dark;
    @apply pt-12;
  }
  .header {
    @apply flex justify-between;
    @apply fixed w-full h-12;
    @apply px-4;
    @apply bg-brand-red shadow;
  }
  .content {
    @apply flex flex-col justify-between;
    @apply flex-grow;
  }
  .footer {
    @apply text-center;
    @apply p-4;
  }
  .nav-item-anchor {
    @apply h-full flex items-center; /* align text middle */
    @apply hover:bg-brand-red-lighten-1;

    @apply px-2;
  }
</style>

// src/components/Page.svelte
<script>
  const navs = [
    { text: 'Docs', href: '/docs' },
    {
      text: 'GitHub',
      href: 'https://github.com/cotowali/cotowali',
      target: '_blank',
      rel: 'external',
    },
  ]
</script>

<header class="header">
  <div class="flex items-center">
    <span>Cotowali</span>
  </div>
  <nav>
    <ul class="flex h-full">
      {#each navs as { text, href, ...attrs} }
        <li><a class="nav-item-anchor hover:bg-brand-red-lighten-1" {href} {...attrs}>{text}</a></li>
      {/each}
    </ul>
  </nav>
</header>

<div class="page">
  {#if $$slots.left }
    <slot name="left" />
  {/if}
  <div class="content">
    <main>
      <slot></slot>
    </main>

    <footer class="footer">
      <p class="text-sm">
      Copyright &copy; 2021 The Cotowali Authors
      </p>
    </footer>
  </div>
  {#if $$slots.right }
    <slot name="right" />
  {/if}
</div>

<style>
  :global(body) {
    @apply text-white;
  }
  .page {
    @apply flex justify-between;
    @apply min-h-full w-full;
    @apply bg-dark;
    @apply pt-12;
  }
  .header {
    @apply flex justify-between;
    @apply fixed w-full h-12;
    @apply px-4;
    @apply bg-brand-red shadow;
  }
  .content {
    @apply flex flex-col justify-between;
    @apply flex-grow;
  }
  .footer {
    @apply text-center;
    @apply p-4;
  }
  .nav-item-anchor {
    @apply h-full flex items-center; /* align text middle */
    @apply px-2;
  }
</style>
